[package]
name = "simdutf8"
version = "0.0.1"
authors = ["Hans Kratz <hans@appfour.com>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# benchmarking
core_affinity = { version = "0.5", optional = true }
criterion = { version = "0.3", optional = true }


[dev-dependencies]


[[bench]]
name = "benchmark"
harness = false

[features]
default = ["std"]

std = []

# Allow fallback to non simd CPUs
allow-non-simd = []

# Force using AVX2 implementation
force-avx2 = []

# Force using SSE4.2 implementation
force-sse42 = []

# don't inline code - used for debugging
no-inline = []

# use branch hints - requires nightly :(
hints = [] # requires nightly

# dependencies only needed for cargo bench
bench = ["criterion", "core_affinity"]