[package]
name = "simdutf8"
version = "0.0.1"
authors = ["Hans Kratz <hans@appfour.com>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# benchmarking, as normally dependencies behind feature flag for faster builds
core_affinity = { version = "0.5", optional = true }
criterion = { version = "0.3", optional = true }
criterion-cycles-per-byte = { version = "0.1.2", optional = true }

[dev-dependencies]


[[bench]]
name = "throughput_pure"
harness = false

[[bench]]
name = "throughput_compat"
harness = false

[[bench]]
name = "throughput_std"
harness = false

[[bench]]
name = "cpb_pure"
harness = false

[[bench]]
name = "cpb_compat"
harness = false

[[bench]]
name = "cpb_std"
harness = false

[features]
default = ["std"]

std = []

# don't inline code - used for debugging
no-inline = []

# use branch hints - requires nightly :(
hints = [] # requires nightly

# dependencies only needed for cargo bench
bench = ["criterion", "criterion-cycles-per-byte", "core_affinity"]

[profile.bench]
lto = true
codegen-units = 1
