[package]
name = "simdutf8"
version = "0.0.1"
authors = ["Hans Kratz <hans@appfour.com>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false

[features]
default = []

# Allow fallback to non simd CPUs
allow-non-simd = []

# don't inline code - used for debugging
no-inline = []

# use branch hints - requires nightly :(
hints = [] # requires nightly