on: [pull_request]
name: benchmark pull requests
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - uses: jasonwilliams/criterion-compare-action@move_to_actions
        env:
          RUSTFLAGS: -C target-feature=+avx2
        with:
          benchName: "benchmark"
          token: ${{ secrets.GITHUB_TOKEN }}
