on: [pull_request]
name: benchmark pull requests
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - uses: rusticstuff/criterion-compare-action@2ff8ad3151dc26fe91e59c22eee6aa985f5e285b
        with:
          benchName: "benchmark"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RUSTFLAGS: -C target-feature=+avx2
