on: [pull_request]
name: benchmark pull requests
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - uses: boa-dev/criterion-compare-action@v2.0.0
        with:
          benchName: "benchmark"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RUSTFLAGS: -C target-feature=+avx2
