name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        simdfeatures: [avx2, sse4.2]
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.toolchain }}
            override: true
      - name: Build
        run: cargo build --verbose
        env:
            RUSTFLAGS: -C target-feature=+${{ matrix.simdfeatures }}
      - name: Run tests
        run: cargo test --verbose
        env:
            RUSTFLAGS: -C target-feature=+${{ matrix.simdfeatures }}

  clippy_check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  benchmark:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: actions/cache@v2
        with:
        path: target/criterion
        key: criterion
      - name: Run benchmark
        run: cargo bench -- --color=always
        env:
            RUSTFLAGS: -C target-feature=+avx2
