name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: playhouse
    strategy:
      matrix:
        toolchain: [stable, nightly]
        arch: [x86_64, i686]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.toolchain }}-${{ matrix.arch }}
            profile: minimal
            override: true
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  clippy_check:
    runs-on: playhouse
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            profile: minimal
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-default-features

  benchmark:
    if: "${{ !startsWith(github.event.commits[0].message, 'export_baseline:') }}"
    runs-on: hurricane
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
            override: true
      - name: Run benchmark
        run: cargo bench --bench benchmark --features=bench -- --color=always --save-baseline new+avx2 --noplot
        env:
          RUSTFLAGS: -C target-feature=+avx2
      - name: Run benchmark
        run: cargo bench --bench benchmark --features=bench -- --color=always --save-baseline new+auto --noplot
      - name: Critcmp comparison
        run: critcmp new+avx2 new+auto baselines/simd+avx2.json baselines/std.json --color=always

  export-baseline:
    if: "${{ startsWith(github.event.commits[0].message, 'export_baseline:') }}"
    runs-on: hurricane
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
            override: true
      - name: Create benchmark baseline
        run: cargo bench --bench benchmark --features=bench,force-avx2 -- --color=always --save-baseline export_baseline --noplot
      - name: Critcmp export
        run: critcmp --export export_baseline > baseline+avx2.json
      - name: Create benchmark baseline
        run: cargo bench --bench benchmark --features=bench,force-sse42 -- --color=always --save-baseline export_baseline --noplot
      - name: Critcmp export
        run: critcmp --export export_baseline > baseline+sse42.json
      - uses: actions/upload-artifact@v2
        with:
          name: baselines
          path: |
            baseline+avx2.json
            baseline+sse42.json

