name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: playhouse
    strategy:
      matrix:
        toolchain: [stable, nightly]
        arch: [x86_64, i686]
        simdfeatures: [avx2, sse4.2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.toolchain }}-${{ matrix.arch }}
            profile: minimal
            override: true
      - name: Build
        run: cargo build --verbose
        env:
            RUSTFLAGS: -C target-feature=+${{ matrix.simdfeatures }}
      - name: Run tests
        run: cargo test --verbose
        env:
            RUSTFLAGS: -C target-feature=+${{ matrix.simdfeatures }}

  clippy_check:
    runs-on: playhouse
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            profile: minimal
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  benchmark:
    if: "${{ !startsWith(github.event.commits[0].message, 'export_baseline:') }}"
    runs-on: hurricane
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
            override: true
      - name: Run benchmark
        run: cargo bench --bench benchmark --features=bench -- --color=always --save-baseline newbase --noplot
        env:
            RUSTFLAGS: -C target-feature=+avx2
      - name: Criterion comparison
        run:  cargo bench --bench=benchmark --features=bench -- --color=always --load-baseline newbase --baseline baseline --noplot
        env:
            RUSTFLAGS: -C target-feature=+avx2
      - name: Critcmp comparison
        run: critcmp baseline newbase --color=always

  export-baseline:
    if: "${{ startsWith(github.event.commits[0].message, 'export_baseline:') }}"
    runs-on: hurricane
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
            override: true
      - name: Create benchmark baseline
        run: cargo bench --bench benchmark --features=bench,allow-non-simd -- --color=always --save-baseline export_baseline --noplot
      - name: Critcmp export
        run: critcmp --export export_baseline > baseline1.json
      - name: Create benchmark baseline
        run: cargo bench --bench benchmark --features=bench,allow-non-simd -- --color=always --save-baseline export_baseline --noplot
        env:
            RUSTFLAGS: -C target-feature=+avx2
      - name: Critcmp export
        run: critcmp --export export_baseline > baseline2.json
      - uses: actions/upload-artifact@v2
        with:
          name: baselines
          path: baseline1.json
          path: baseline2.json

